# Generated by Django 3.2.9 on 2021-11-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('comonmistake_1', models.CharField(max_length=128)),
                ('comonmistake_2', models.CharField(max_length=128)),
                ('comonmistake_3', models.CharField(max_length=128)),
            ],
        ),
    ]
